name: Terraform Deploy (disabled)

on: []

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow disabled
        run: echo "terraform-deploy workflow temporarily disabled"
