name: Terraform Destroy (disabled)

on: []

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow disabled
        run: echo "terraform-destroy workflow temporarily disabled"
